spring:
  application:
    name: elk
  zipkin:
    base-url: http://localhost:9411

logging:
  file:
    path: /Users/jaeyeol/workspace/spring-msa-test/logs/elk

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}